name: Amber Script
description: Run arbitrary Amber scripts.
branding:
  color: orange
  icon: code
inputs:
  script:
    description: The script to run
    required: true
  amber-version:
    default: 0.5.1-alpha
  enable-cache:
    description: Whether to cache Amber binaries and the compiled bash scripts
    default: true
  cache-path:
    description: >-
      The path to store Amber binaries and the compiled bash scripts.
      If empty string is given, the used path depends on the runner.
    default: ""
runs:
  using: composite
  steps:
    - name: Cache compiled script
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      if: inputs.enable-cache
      with:
        path: ${{ inputs.cache-path != '' && format('{0}/dest', inputs.cache-path) || (runner.os == 'Linux' && '/home/runner/.amber-script-action/dest' || '/Users/runner/.amber-script-action/dest') }}
        key: amber-script-action-${{ runner.os }}-script-${{ inputs.amber-version }}
    - uses: lens0021/setup-amber@2e13727a77c839ecb407da90736cc07b8d68cd42 # v1.1.0
      with:
        amber-version: ${{ inputs.amber-version }}
        enable-cache: ${{ inputs.enable-cache }}
        cache-path: ${{ inputs.cache-path != '' && format('{0}/actions/setup-amber', inputs.cache-path) || (runner.os == 'Linux' && '/home/runner/.amber-script-action/actions/setup-amber' || '/Users/runner/.amber-script-action/actions/setup-amber') }}
        bin-path: ${{ inputs.cache-path != '' && format('{0}/bin/amber-{1}', inputs.cache-path, inputs.amber-version) || (runner.os == 'Linux' && format('/home/runner/.amber-script-action/bin/amber-{0}', inputs.amber-version) || format('/Users/runner/.amber-script-action/bin/amber-{0}', inputs.amber-version)) }}
    - shell: bash
      env:
        AMBER_SCRIPT_CACHE_PATH_INPUT: ${{ inputs.cache-path }}
        AMBER_SCRIPT_RUNNER_OS: ${{ runner.os }}
        AMBER_SCRIPT_CONTENT: ${{ inputs.script }}
        AMBER_SCRIPT_VERSION: ${{ inputs.amber-version }}
      run: |
        # Build and run script
        bash "${{ github.action_path }}/dist/main.sh"
