name: Amber Script
description: Run arbitrary Amber scripts.
branding:
  color: orange
  icon: code
inputs:
  script:
    description: The script to run
    required: true
  amber-version:
    default: 0.4.0-alpha
  enable-cache:
    description: Whether to cache Amber binaries and the compiled bash scripts
    default: true
  cache-path:
    description: >-
      The path to store Amber binaries and the compiled bash scripts.
      If empty string is given, the used path depends on the runner.
    default: ""
  internal-eof-word:
    description: Internal only. Do not use this.
    default: END_OF_GIVEN_AMBER_SCRIPT
runs:
  using: composite
  steps:
    - id: hash-script
      shell: bash
      env:
        SCRIPT_CONTENT: ${{ inputs.script }}
        EOF_WORD: ${{ inputs.internal-eof-word }}
      run: |
        # Make cache key for given script
        # Note: macos runner does not have sha256sum.
        {
          echo -n 'hash='
          printf '%s\n' "$SCRIPT_CONTENT" | openssl sha256 | cut -d' ' -f 2
        } >> "$GITHUB_OUTPUT"
    - shell: bash
      env:
        CACHE_PATH_INPUT: ${{ inputs.cache-path }}
      run: |
        # Export cache path
        if [ -n "$CACHE_PATH_INPUT" ]; then
          {
            echo "amber_cache_path<<CACHE_PATH_EOF"
            echo "$CACHE_PATH_INPUT"
            echo "CACHE_PATH_EOF"
          } >> "$GITHUB_ENV"
        elif [ "${{ runner.os }}" == "Linux" ]; then
          echo "amber_cache_path=/home/runner/.amber-script-action" >> "$GITHUB_ENV"
        else
          echo "amber_cache_path=/Users/runner/.amber-script-action" >> "$GITHUB_ENV"
        fi
    - name: Cache compiled script
      uses: actions/cache@v3
      if: inputs.enable-cache
      with:
        path: ${{ env.amber_cache_path }}/dest
        key: amber-script-action-${{ runner.os }}-script-${{ inputs.amber-version }}
    - uses: lens0021/setup-amber@ef483e92d1524f089fb18ddc0b0d7949123073d7 # v1.1.0
      with:
        amber-version: ${{ inputs.amber-version }}
        enable-cache: ${{ inputs.enable-cache }}
        cache-path: ${{ env.amber_cache_path }}/actions/setup-amber
        bin-path: ${{ env.amber_cache_path }}/bin/amber-${{ inputs.amber-version }}
    # TODO: Convert this to amber-script-action.
    # This includes a here-document expression, so hard to convert.
    - shell: bash
      env:
        AMBER_CACHE_PATH: ${{ env.amber_cache_path }}
        SCRIPT_CONTENT: ${{ inputs.script }}
        AMBER_VERSION: ${{ inputs.amber-version }}
        SCRIPT_HASH: ${{ steps.hash-script.outputs.hash }}
      run: |
        # Build the given script
        if [ -e "${AMBER_CACHE_PATH}/dest/${SCRIPT_HASH}.sh" ]; then
          echo "::debug::A compiled bash script found. Skip building."
        else
          mkdir -p "${AMBER_CACHE_PATH}/tmp"
          printf '%s\n' "$SCRIPT_CONTENT" > "${AMBER_CACHE_PATH}/tmp/${SCRIPT_HASH}.ab"
          mkdir -p "${AMBER_CACHE_PATH}/dest"
          "${AMBER_CACHE_PATH}/bin/amber-${AMBER_VERSION}" build "${AMBER_CACHE_PATH}/tmp/${SCRIPT_HASH}.ab" "${AMBER_CACHE_PATH}/dest/${SCRIPT_HASH}.sh"
        fi
    - shell: bash
      env:
        AMBER_CACHE_PATH: ${{ env.amber_cache_path }}
        SCRIPT_HASH: ${{ steps.hash-script.outputs.hash }}
      run: |
        # Run the compiled script
        bash "${AMBER_CACHE_PATH}/dest/${SCRIPT_HASH}.sh"
